"""empty message

Revision ID: 0063afe3c33f
Revises: 2e89980b7945
Create Date: 2024-09-28 23:17:28.677592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0063afe3c33f'
down_revision: Union[str, None] = '2e89980b7945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('content', sa.Text(), nullable=True, comment='내용'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'content')
    # ### end Alembic commands ###
