"""empty message

Revision ID: 2e89980b7945
Revises: a45a09509bd1
Create Date: 2024-09-28 18:37:33.579092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e89980b7945'
down_revision: Union[str, None] = 'a45a09509bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(), nullable=False, comment='닉네임'))
    op.drop_index('ix_user_nickname', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=1)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
