"""empty message

Revision ID: a45a09509bd1
Revises: 
Create Date: 2024-09-28 18:24:49.327214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45a09509bd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False, comment='닉네임'),
    sa.Column('password', sa.String(), nullable=False, comment='비밀번호'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=True)
    op.create_table('friend_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False, comment='팔로워 아이디'),
    sa.Column('following_id', sa.Integer(), nullable=False, comment='팔로잉 아이디'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name=op.f('fk_friend_relation_follower_id_user')),
    sa.ForeignKeyConstraint(['following_id'], ['user.id'], name=op.f('fk_friend_relation_following_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friend_relation'))
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='유저 아이디'),
    sa.Column('category', sa.Integer(), nullable=False, comment='카테고리'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='생성일'),
    sa.Column('duration', sa.Integer(), nullable=False, comment='시간 (초)'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_history_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('friend_relation')
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
